### PR TITLE
First time to refactor test

### PR DESCRIPTION
**Pull request by PabloDeo**

### CODE REVIEW

**Comment by PabloDeo** [comment]
The main file has been adjusted for the property files

**Comment by joov** [comment]
Cannnot merge your latest changes, especially on Main2.java Could you comment on your changes?

**Comment by PabloDeo** [comment]
I did not push anything recently. I am not sure but it is possible that I
have done something wrong.

Is it possible for you to create a new branch? I have tried to reset a
commit before, with no success.

I will come back to the issue of code sharing. (If you want, I could send
new version of code to you.)

**Comment by joov** [comment]
Closing request

**Pull request merged**
