### PR TITLE
Both Model1 java file present

### PR DESCRIPTION
**Pull request by PabloDeo**

### CODE REVIEW

**Review by joov — APPROVED** [review]
Looks good

**Comment by joov** [comment]
Looks good

**Comment by joov** [comment]
Please avoid any fixed Path names. They shoud all be configurable.
Best to use a property-file where the things can be edited. It is neccessary, that other people (like me (-:) can use your code as well!

**Comment by PabloDeo** [comment]
@joov  I am not exactly sure about "Best to use a property-file where the things can be edited." Am I correct that I should set a public static variable in the class Util for the Path names? (such as "/csvs")

**Review by joov — APPROVED** [review]
I Approve the changes so that I can use them but I hope that you will add comments to the new classes / public methods soon :-)

**Comment by joov** [comment]
Pull request merged

**Pull request closed without merging**
